### ISSUE TITLE
#TK01 Realizar la conexión de la app móvil a firebase, para así poder visualizar las mismas recetas en ambas aplicaciones.

### ISSUE THREAD

**Issue by MarianelaAgostini** [MarianelaAgostini/ISPC2024#37]

**Comment by viktoryia40** [comment]
Hemos realizado la conexión de la app móvil a Firebase. Ahora, los usuarios pueden visualizar las mismas recetas en ambas aplicaciones, asegurando la consistencia de la información y mejorando la experiencia del usuario. La configuración de Firebase se ha completado correctamente y se han realizado pruebas para verificar el correcto funcionamiento de la integración.

**Comment by FabioLunaa** [comment]
El trabajo de la conexión se ha realizado en conjunto con una integrante de mi equipo, la conexion se ha realizado con éxito y funciona de forma positiva tanto en la app móvil como en la app web. Trabajo terminado.
